### ISSUE TITLE
Kind of beginner in programming and really messed up with programming thoughts while learning C language and looking for a real help please

### ISSUE THREAD

**Issue by Hello-Saurabh** [cs-books/influential-cs-books#12]
Right now I have learn basic C programming but I am stuck with what are the things that needed in beginning for C architecture to learn.
Like right now I have learn about Basic C programming from the C programming language by kernighan and Ritchie, then I bought data structure and algorithm analysis in C  by Mark Allen Weiss,with 'dicreate mathematics and its application with combinatorics and graph theory but  Kenneth h Rosen' to learn in depth but I am in doubt whether is it correct  sequence to learn or can u help me out in suggesting the correct sequence to learn the whole basic C architecture with books or internet , whatever is possible thank you.

**Comment by fire-eggs** [comment]
You're more likely to get some feedback from the [Github Community] (https://github.community/). Especially since this repo hasn't been updated in years ...
